zephyr_cours_homepage:
    path:     /
    defaults: { _controller: ZephyrCoursBundle:Default:index }

api_get_student:
    path:   /search/{query}
    defaults: { _controller: ZephyrCoursBundle:Default:search }

zephyr_cours_mycourse:
    path:   /mycourse
    defaults: { _controller: ZephyrCoursBundle:Default:mycourse }

zephyr_cours_listcourse:
    path:   /listcourse
    defaults: { _controller: ZephyrCoursBundle:Default:listcourse }