zephyr_cours_homepage:
    path:     /
    defaults: { _controller: ZephyrCoursBundle:Default:index }

api_get_student:
    path:   /search/{query}
    defaults: { _controller: ZephyrCoursBundle:Default:search }

zephyr_cours_mycourse:
    path:   /my-course
    defaults: { _controller: ZephyrCoursBundle:Default:mycourse }

zephyr_cours_listcourse:
    path:   /list-course
    defaults: { _controller: ZephyrCoursBundle:Default:listcourse }

zephyr_cours_admin:
    path:     /admin
    defaults: { _controller: ZephyrCoursBundle:Default:admin }

zephyr_cours_show:
    path:     /admin/{id}
    defaults: { _controller: ZephyrCoursBundle:Default:show }

zephyr_cours_addstudent:
    path:     /add-student/{id}
    defaults: { _controller: ZephyrCoursBundle:Default:addstudent }

zephyr_cours_addprof:
    path:     /add-prof/{id}
    defaults: { _controller: ZephyrCoursBundle:Default:addprof }

zephyr_change_password:
    path:   /change-password
    defaults: { _controller: ZephyrCoursBundle:Default:changepassword }

zephyr_token_password:
    path:   /change-password/{id}/{token}
    defaults: { _controller: ZephyrCoursBundle:Default:tokenpassword }

zephyr_cours_del:
    path:   /cours-del/{id}/{cours_id}/{password}
    defaults: { _controller: ZephyrCoursBundle:Default:coursdel }

zephyr_cours_remove:
    path:   /cours-remove/{id}/{cours_id}/{password}
    defaults: { _controller: ZephyrCoursBundle:Default:coursremove }