services:
    zephyr_cours.course:
        class: Zephyr\CoursBundle\Form\CourseType
        tags:
            - { name: form.type, alias: course }

    zephyr_cours.type.unit_selector:
        class: Zephyr\CoursBundle\Form\UnitSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: unit_selector }