zephyr_cours:
    resource: "@ZephyrCoursBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:     /login
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::login.html.twig'

login_check:
    path: /login_check